# Generated by Django 3.2.12 on 2024-10-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_auto_20241017_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('score', models.FloatField()),
                ('url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('ontime', models.CharField(blank=True, max_length=100, null=True)),
                ('production_company', models.TextField(blank=True, null=True)),
                ('production_country', models.CharField(blank=True, max_length=100, null=True)),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('geted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
    ]
